config/routes.rb
Qiongerdai::Application.routes.draw do

  resources :comments

  resources :archives do
    get 'feed', :on => :collection
  end

  namespace :admin do
    match '/' => 'console#index',:as => :console
    match '/summary' => 'console#install_summary'
    resources :things,:categories,:client_apps
    resources :archives do
      get 'thumb', :on => :member
      put 'crop', :on => :member
      put 'ok', :on => :member
      put 'allocate', :on => :collection
      put 'unlock', :on => :member
    end
  end

  resources :products
  resources :things
  resources :categories
  
  match 'ping' => 'pings#create'
  match 'activate' => 'pings#activate'
  
  match 'client/version' => 'versions#last_build_number'
  match 'client/dl' => 'versions#down_last_build'

  root :to => 'archives#index'

end

app/models/thing.rb
class Thing < ActiveRecord::Base
  belongs_to :category
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  # GET /things
  # GET /things.xml
  def index
    @things = Thing.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @things }
    end
  end

  # GET /things/1
  # GET /things/1.xml
  def show
    @thing = Thing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @thing }
    end
  end

  # GET /things/new
  # GET /things/new.xml
  def new
    @thing = Thing.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @thing }
    end
  end

  # GET /things/1/edit
  def edit
    @thing = Thing.find(params[:id])
  end

  # POST /things
  # POST /things.xml
  def create
    @thing = Thing.new(params[:thing])

    respond_to do |format|
      if @thing.save
        format.html { redirect_to(@thing, :notice => 'Thing was successfully created.') }
        format.xml  { render :xml => @thing, :status => :created, :location => @thing }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @thing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /things/1
  # PUT /things/1.xml
  def update
    @thing = Thing.find(params[:id])

    respond_to do |format|
      if @thing.update_attributes(params[:thing])
        format.html { redirect_to(@thing, :notice => 'Thing was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @thing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.xml
  def destroy
    @thing = Thing.find(params[:id])
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to(things_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :alias %><br />
    <%= f.text_field :alias %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<h1>Listing things</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Alias</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @things.each do |thing| %>
  <tr>
    <td><%= thing.title %></td>
    <td><%= thing.alias %></td>
    <td><%= thing.category %></td>
    <td><%= link_to 'Show', thing %></td>
    <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
    <td><%= link_to 'Destroy', thing, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Thing', new_thing_path %>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render 'form' %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @thing.title %>
</p>

<p>
  <b>Alias:</b>
  <%= @thing.alias %>
</p>

<p>
  <b>Category:</b>
  <%= @thing.category %>
</p>


<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>