config/routes.rb
Qiongerdai::Application.routes.draw do

  resources :comments

  resources :archives do
    get 'feed', :on => :collection
  end

  namespace :admin do
    match '/' => 'console#index',:as => :console
    match '/summary' => 'console#install_summary'
    resources :things,:categories,:client_apps
    resources :archives do
      get 'thumb', :on => :member
      put 'crop', :on => :member
      put 'ok', :on => :member
      put 'allocate', :on => :collection
      put 'unlock', :on => :member
    end
  end

  resources :products
  resources :things
  resources :categories
  
  match 'ping' => 'pings#create'
  match 'activate' => 'pings#activate'
  
  match 'client/version' => 'versions#last_build_number'
  match 'client/dl' => 'versions#down_last_build'

  root :to => 'archives#index'

end

app/models/archive.rb
require 'zip/zipfilesystem'
require 'devil'

class Archive < ActiveRecord::Base
  belongs_to :provider

  validates_uniqueness_of :url, :message => "DUPLICATED"
  validates_uniqueness_of :uid, :message => "DUPLICATED"

  TINY_THUMB='thumb48.jpg'
  SMALL_THUMB='thumb96.jpg'
  BIG_THUMB='thumb150.jpg'
  # Archive status
  # new => analyzed => synced => locked(being verified by some admin) <=> ok(published) => deleted(ignored)
  DELETED=-2
  IGNORE=-1
  NEW=0
  ANALYZED=1
  SYNCED=2
  LOCKED=3
  OK=4
  OLD=5
  
  def content_dom
    return @dom if not @dom.blank?
    @dom=Nokogiri::HTML(self.content)
  end

  # Remove fixed width of table elements
  def adjust_table_width
    content_dom.xpath('//table').each do |ele|
      ele['width']=''
    end
    self.update_attribute('content',content_dom.to_html)
  end
  
  # generate mobile type html file
  # 
  def write_mobile_html
    File.open(File.join(self.abs_img_dir,"#{self.id}.html"),"w") do |html|
      html.puts('<?xml version="1.0" encoding="UTF-8"?>')
      html.puts('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML Basic 1.1//EN" "http://www.w3.org/TR/xhtml-basic/xhtml-basic11.dtd">')
      html.puts('<html><head>')
      html.puts("<title>#{self.title}</title>")
      html.puts('<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">')
      html.puts('<meta http-equiv="content-type" content="text/html; charset=UTF-8">')
      html.puts('<style type="text/css">')
      html.puts('.autosize{max-width:100%;}')
      html.puts('.fitscreen{max-width:100%;}')
      html.puts('</style>')
      html.puts('</head>')
      html.puts('<body>')
      html.puts("<h2>#{self.title}</h2>")
      html.puts('<div>')
      doc=Nokogiri::HTML(self.content)
      doc.xpath("//img[@class='autosize']").each { |img| img["src"]=img["src"].sub(/\/images\/archives\/\d+\/pics_[hml]\//,'') }
      html.puts(doc.to_html)
      html.puts('</div>')
      html.puts("<p>原文链接: <a href='#{self.url}'>#{self.url.truncate(30)}</a></p>")
      html.puts('</body></html>')
    end
  end

  # FIXME should generate differnet img size package
  def to_zip
    write_mobile_html
    resize_imgs
    pack 'h'
    pack 'm'
    pack 'l'
    FileUtils.chmod 0644, [to_abs(zip_url_path('h')),to_abs(zip_url_path('m')),to_abs(zip_url_path('l'))]
  end
  
  def resize_imgs
    FileUtils.rm_rf to_abs(File.join(root_url_dir,'pics_l'))
    FileUtils.rm_rf to_abs(File.join(root_url_dir,'pics_m'))
    FileUtils.mkdir_p(to_abs(File.join(root_url_dir,'pics_l')))
    FileUtils.mkdir_p(to_abs(File.join(root_url_dir,'pics_m')))
    Dir.foreach(self.abs_img_dir) do |img|
      next if img.start_with?('.')
      # resize img
      if img.end_with? 'html'
        FileUtils.cp(abs_img_path(img,'h'),abs_img_path(img,'m'))
        FileUtils.cp(abs_img_path(img,'h'),abs_img_path(img,'l'))
      else
        di=Devil.with_image(abs_img_path(img,'h')) rescue next
        m_q_img=di.dup.resize(*cal_new_size(di.width,di.height,480))
        m_q_img.save(abs_img_path(img,'m'), :quality => 65 )
        l_q_img=di.dup.resize(*cal_new_size(di.width,di.height,320))
        l_q_img.save(abs_img_path(img,'l'), :quality => 65 )
        # ImageScience.with_image(abs_img_path(img,'h')) do |is_pic|
        #   if is_pic.width>480
        #     new_height=(is_pic.height.to_f/is_pic.width) * 480
        #     is_pic.resize(480,new_height){|np| np.save(abs_img_path(img,'m'))}
        #   else
        #     is_pic.save(abs_img_path(img,'m'))
        #   end
        #   if is_pic.width>320
        #     new_height=(is_pic.height.to_f/is_pic.width) * 320
        #     is_pic.resize(320,new_height){|np| np.save(abs_img_path(img,'l'))}
        #   else
        #     is_pic.save(abs_img_path(img,'l'))
        #   end          
        # end
      end
    end
  end
  
  def pack(quality='h')
    # generate origin quality zip file 
    zip_file=to_abs(zip_url_path(quality))
    FileUtils.rm zip_file, :force => true
    Zip::ZipFile.open(zip_file,Zip::ZipFile::CREATE) do |zip|
      zip.dir.mkdir("#{self.id}")
      Dir.foreach(self.abs_img_dir(quality)) do |img|
        next if img.start_with?('.')
        zip.add("#{self.id}/#{img}",abs_img_path(img,quality))
      end
    end     
  end

  # deprecated
  # Used for update img['src'] attributes after archive id has changed
  # def refresh_img_url(old_id)
  #   return true if self.id==old_id.to_i
  #   ns=content_dom
  #   ns.xpath('//img').each do |pi|
  #     pi['src']=pi['src'].sub(/\/images\/archives\/\d+\//,"/images/archives/#{self.id}/") if pi['class']=='autosize' && pi['src']=~/\/images\/archives\/\d+\//
  #     logger.debug("AAAA => #{pi['src']}")
  #   end
  #   self.thumbnail=self.thumbnail.sub(/\/images\/archives\/\d+\//,"/images/archives/#{self.id}/")
  #   self.content=ns.to_html 
  #   self.save
  # end
  
  def cal_new_size(width,height,max_width)
    if width>max_width
      new_height=(height.to_f/width) * max_width
      return max_width,new_height
    else
      return width,height
    end
  end

  def all_image_filenames(quality='h')
    return @images unless @images.blank?
    @images=[]
    Dir.foreach(self.abs_img_dir(quality)) do |file|
      @images<<file unless file.start_with?('.') && file.end_with?('html')
    end
    @images
  end

  def abs_img_path(img_name,quality='h')
    File.join(abs_img_dir(quality),img_name)
  end

  def img_url_path(img_name,quality='h')
    File.join(img_url_dir(quality),img_name)
  end

  # dir part of the image url
  def img_url_dir(quality='h')
    File.join(self.root_url_dir,"pics_#{quality}")
  end

  # absolute path of the dir to save images of an archive
  def abs_img_dir(quality='h')
    aid=File.join(Rails.public_path,img_url_dir(quality))
    FileUtils.mkdir_p(aid) unless File.exists? aid
    aid
  end

  # FIXME has different size of package
  def zip_url_path(quality="h")
    File.join(self.root_url_dir,"#{self.id}_#{quality}.zip")
  end  
  
  def root_url_dir()
    return @srud unless @srud.blank?
    @srud=File.join("/images/archives",self.id.to_s)
    # FileUtils.mkdir_p(@srud) unless File.exists? @srud
    # @srud
  end
  
  def to_abs(path)
    File.join(Rails.public_path,path)
  end

  def thumb_filenames()
    return BIG_THUMB,SMALL_THUMB,TINY_THUMB #"thumb150","thumb96","thumb48"
  end

  def small_thumb_url_path
    img_url_path(SMALL_THUMB)
  end
  def tiny_thumb_url_path
    img_url_path(TINY_THUMB)
  end
  def big_thumb_url_path
    img_url_path(BIG_THUMB)
  end

  def locked?
    self.status==LOCKED
  end

  def ok?
    self.status==OK
  end

  def analyzed?
    self.status==ANALYZED    
  end

  def synced?
    self.status==SYNCED
  end

end

app/controllers/admin/archives_controller.rb
require 'fileutils'
class Admin::ArchivesController < Admin::ConsoleController

  before_filter :authorized?, :except => :create
  before_filter :load_archive, :except => [:index,:create,:new,:allocate]
  # GET /archives
  # GET /archives.xml
  def index
    @title="文章列表"
    status=params[:status].blank? ? Archive::SYNCED : (params[:status].to_i rescue Archive::SYNCED)
    puts "AAAAAAAAAAAAAA=> #{status}"
    @archives = Archive.where(["status=?",status]).order("created_at desc").page(params[:page]).per(15)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @archives }
    end
  end

  def ok
    @archive.to_zip
    @archive.update_attribute('status',Archive::OK)
    # delete cached pages
    cached_pages=File.join(Rails.public_path,'archives/*')
    FileUtils.rm Dir.glob(cached_pages), :force => true 
    # expire_page feed_archives_path
    respond_to do |wants|
      wants.html { redirect_to admin_archives_path(:status => 1)}
    end
    
  end

  def thumb
    @images=@archive.all_image_filenames
    @source=params[:source]||@archive.thumbnail
    @source=@archive.img_url_path(@source,'h') if @source[0]!=47 #'/' is 47
    render :layout => false
  end

  def crop
    thumb_source=File.basename(params[:source])
    big,small,tiny=@archive.thumb_filenames()
    ImageScience.with_image(@archive.abs_img_path(thumb_source,'h')) do |pic|
      left=params[:x1].to_i
      top=params[:y1].to_i
      right=params[:x1].to_i+params[:width].to_i
      bottom=params[:y1].to_i+params[:height].to_i
      pic.with_crop(left,top,right,bottom) do |pic|
        pic.resize(150,150) {|np| np.save(@archive.abs_img_path(big,'h'))}
        pic.resize(96,96) {|sp| sp.save(@archive.abs_img_path(small,'h'))}
        pic.resize(48,48) {|tp| tp.save(@archive.abs_img_path(tiny,'h'))}
      end
    end
    @archive.update_attribute('thumbnail',@archive.img_url_path(big,'h'))
     respond_to do |wants|
       wants.html{ redirect_to admin_archive_path(@archive) }
     end
     
  end

  # GET /admin/archives/1
  # GET /admin/archives/1.xml
  def show
    @title="编辑文章"
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @archive }
    end
  end

  # GET /archives/new
  # GET /archives/new.xml
  def new
    @archive = Archive.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @archive }
    end
  end

  # GET /archives/1/edit
  def edit
    @archive = Archive.find(params[:id])
  end

  # POST /archives
  # POST /archives.xml
  # This method is only used for sychronize archives bettween crawl and web servers.
  # FIXME IP address and password check should be added to forbidden illegal request
  # FIXME if there is a same url archive existed then ignore the uploaded one.
  def create
    ok=false
    begin
      @archive = Archive.new(params[:archive])
      @archive.id=params[:archive][:id]
      @archive.save!
      #@archive.id=params[:archive][:id] # Since id can't be set mass-assigned.
      upload_io=params[:archive_imgs]
      # Save zip file to local 
      zip_file= File.join(@archive.abs_img_dir,"#{@archive.id}.zip")#upload_io.original_filename)
      File.open(zip_file,'w') { |f| f.write(upload_io.read)}
      system("unzip #{zip_file} -d #{@archive.abs_img_dir}")
      @archive.refresh_img_url(params[:archive][:id])
      #FileUtils.rm zip_file, :force => true
      ok=true
    rescue ActiveRecord::RecordInvalid => e
      # Resumed that only duplicated url can cause active record validation failed.
      # So ignore this error and return HTTP 201 to upload client.
      logger.error("#{e.class} => #{e.message}")
      @archive.errors.each { |err| logger.error(err) }
      ok=true
    rescue Exception => e 
      ok=false
    end

    respond_to do |format|
      if ok #@archive.save
        format.html { redirect_to([:admin,@archive], :notice => 'Archive was successfully created.') }
        format.xml  { render :xml => @archive, :status => :created, :location => @archive }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @archive.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /archives/1
  # PUT /archives/1.xml
  def update

    respond_to do |format|
      if @archive.update_attributes(params[:archive])
        format.html { redirect_to([:admin,@archive], :notice => 'Archive was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @archive.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.xml
  def destroy
    @archive.update_attribute('status',Archive::DELETED)

    respond_to do |format|
      format.html { redirect_to(admin_archives_path :status => 1 ) }
      format.xml  { head :ok }
    end
  end

  def allocate
    archive=Archive.where("status=?",Archive::SYNCED).order('created_at desc').first  
    archive.update_attribute('status',Archive::LOCKED)
    redirect_to admin_archive_path(archive)
  end

  def unlock
    @archive.update_attribute('status',Archive::SYNCED)
    redirect_to admin_console_path
  end

  def load_archive
    @archive=Archive.find(params[:id])
  end
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController

  caches_page :feed
  
  # GET /archives
  # GET /archives.xml
  def index
    @archives = Archive.where(["status=?",Archive::OK]).order("updated_at desc").page(params[:page]).per(15)

    respond_to do |format|
      format.html # index.html.erb
      format.mobile {}
      format.xml  { render :xml => @archives }
    end
  end

  def feed
    @archives = Archive.where(["status=?",Archive::OK]).order("updated_at desc").limit(8)
    #request.format=:xml
    respond_to do |format|
      format.json do 
        render :json => @archives 
      end
      format.xml { render :layout => false, :content_type => "application/rss"  }
    end
  end

  # GET /archives/1
  # GET /archives/1.xml
  def show
    @archive = Archive.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @archive }
    end
  end

  # GET /archives/new
  # GET /archives/new.xml
  def new
    @archive = Archive.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @archive }
    end
  end

  # GET /archives/1/edit
  def edit
    @archive = Archive.find(params[:id])
  end

  # POST /archives
  # POST /archives.xml
  def create
    @archive = Archive.new(params[:archive])

    respond_to do |format|
      if @archive.save
        format.html { redirect_to(@archive, :notice => 'Archive was successfully created.') }
        format.xml  { render :xml => @archive, :status => :created, :location => @archive }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @archive.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /archives/1
  # PUT /archives/1.xml
  def update
    @archive = Archive.find(params[:id])

    respond_to do |format|
      if @archive.update_attributes(params[:archive])
        format.html { redirect_to(@archive, :notice => 'Archive was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @archive.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.xml
  def destroy
    @archive = Archive.find(params[:id])
    @archive.destroy

    respond_to do |format|
      format.html { redirect_to(archives_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/archives_helper.rb
module Admin::ArchivesHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/views/admin/archives/_archive.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<div class="archive">
  <div class="main">
    <h2><%= link_to truncate_u(archive.title,25),admin_archive_path(archive),:title => archive.title  %></h2>
    <div class="content"><%= archive.desc %></div>
    <div class="info">
      <div class="tail"><%= archive.locked? ? "文章已经被锁定(被编辑)" : "" %></div>
      <p class="tail">
        <%= link_to "查看文章", archive_path(archive) %>&nbsp;
      </p>
    </div>
  </div>
  <% unless archive.thumbnail.blank? %>
  <img src="<%= archive.thumbnail %>" alt="" class="thumbnail"/>
  <% end %>
  <p style="clear:both;"></p>
</div>

app/views/admin/archives/_form.html.erb
<%= form_for([:admin,@archive]) do |f| %>
  <% if @archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

      <ul>
      <% @archive.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br />
    <%= f.text_field :thumbnail %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :analyzed %><br />
    <%= f.check_box :analyzed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/archives/edit.html.erb
<h1>Editing archive</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@archive] %> |
<%= link_to 'Back', admin_archives_path %>

app/views/admin/archives/index.html.erb
<%= paginate @archives %>
<% @archives.each do |archive| %>
  <%= render archive %>
<% end %>

app/views/admin/archives/new.html.erb
<h1>New archive</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_archives_path %>

app/views/admin/archives/show.html.erb
<% content_for :admin_menu do %>
  <li>
    <%= link_to "编辑缩略图", thumb_admin_archive_path(@archive) %>
  </li>
  <li>
  <%= link_to "发布这个文章", ok_admin_archive_path(@archive), :method => 'put' %>
  </li>
  <li>
  <%= link_to "删除这篇文章", admin_archive_path(@archive), :method => 'delete' %>
  </li>
  <li>
  <%= link_to "放弃编辑", unlock_admin_archive_path(@archive), :method => 'put' %>
  </li>
<% end %>

<h2 id="title"><%= @archive.title %></h2>
<div>
  <%= @archive.content.html_safe %>
</div>
<h2 id="heading">编辑文章简介</h2>
<p>
  <b>Desc:</b>
  <%= @archive.desc %>
</p>
<p>
  <%= link_to @archive.url %>
</p>
<%= link_to "Back to Console", admin_console_path %>

app/views/admin/archives/thumb.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit thumbnail image</title>
  <%= javascript_include_tag "Jcrop/js/jquery.min.js","Jcrop/js/jquery.Jcrop.min.js" %>
  <%= stylesheet_link_tag "/javascripts/Jcrop/css/jquery.Jcrop.css" %>
</head>
<body>
  <div class="section header">
<ul>
  <% for img in @images %>
    <li style="display:inline">
      <a href="<%= thumb_admin_archive_path(@archive, :source => img) %>">
      <%= image_tag @archive.img_url_path(img), :style => "max-width:150px;"  %>
      </a>
    </li>
  <% end %>
</ul>

 </div>
  <div class="section">
    <div id="crop_container">
      <script type="text/javascript" charset="utf-8">
        $(window).load(function(){
          var crop=$.Jcrop('#thumb',{aspectRatio: 1,bgOpacity:.4,onChange: setValue,minSize : [96,96]});
          
          var dim=crop.getBounds();
          //crop.setSelect([dim[0]/2-40,80,dim[1]/2,80]);
          $('#reset_o').click(function(e) {
            crop.animateTo([dim[0]/2-40,80,dim[1]/2,80]);
          });
          function setValue(c)
          {
            $('#x1').val(c.x);
            $('#y1').val(c.y);
            $('#w').val(c.w);
            $('#h').val(c.h);
          }
          setValue(crop.tellScaled());

        });
      </script>
      <div class="msg"><p class="info">拖拽选框和改变选框的大小，剪切出美丽的大头像！&nbsp;</p></div>
      <div>
        <%= image_tag @source, :id => "thumb", :name => "thumb"  %>
      </div>
      <% form_tag(crop_admin_archive_path(@archive),:method => :put) do %>
        <div class="hidden">
          <input type="text" name="head" value="true">
          <input type="text" name="x1" id="x1" />
          <input type="text" name="y1" id="y1" />
          <input type="text" name="width" id="w" />
          <input type="text" name="height" id="h" />
          <input type="hidden" name="source" value="<%= @source %>"/>
        </div><p class="h20"></p>
        <p class="center"><%= submit_tag '就这样了，剪裁吧！',:class=>"l-long-btn" %></p>
      <% end %>
    </div>

  </div>
</body>
</html>