config/routes.rb
Qiongerdai::Application.routes.draw do

  resources :comments

  resources :archives do
    get 'feed', :on => :collection
  end

  namespace :admin do
    match '/' => 'console#index',:as => :console
    match '/summary' => 'console#install_summary'
    resources :things,:categories,:client_apps
    resources :archives do
      get 'thumb', :on => :member
      put 'crop', :on => :member
      put 'ok', :on => :member
      put 'allocate', :on => :collection
      put 'unlock', :on => :member
    end
  end

  resources :products
  resources :things
  resources :categories
  
  match 'ping' => 'pings#create'
  match 'activate' => 'pings#activate'
  
  match 'client/version' => 'versions#last_build_number'
  match 'client/dl' => 'versions#down_last_build'

  root :to => 'archives#index'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end

  def show_title?
    @show_title
  end
#
#  def stylesheet(*args)
#    content_for(:head) { stylesheet_link_tag(*args.map(&:to_s)) }
#  end
#
#  def javascript(*args)
#    args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
#    content_for(:head) { javascript_include_tag(*args) }
#  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>美丽日志</title>
  <meta content="text/html; charset=UTF-8" http-equiv="content-type">
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="wrapper section header">
    <ul id="navigation">
      <li><%= link_to '美丽日志',root_path %></li>
      <li><%= link_to '百宝箱',root_path %></li>
      <li><%= link_to '宝贝签到', new_product_path %></li>
      <li><%= link_to 'admin',admin_console_path %></li>
    </ul>
  </div>
  <div class="wrapper">
    <div id="main">
    <div class="section">
    <%= yield %>
    </div>
    </div>
    <div id="side">
      <ul class="tops">
        <% for ha in @hot_archives %>
          <li><%= link_to truncate_u(ha.title,15), ha, :title => ha.title %></li>
        <% end %>
      </ul>
    </div>
    <p class="clear"></p>
  </div>
</body>
</html>

app/views/layouts/application.mobile.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML Basic 1.1//EN"
    "http://www.w3.org/TR/xhtml-basic/xhtml-basic11.dtd">
<html>
  <head>
    <title></title>
    <%= stylesheet_link_tag "mobile.css" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  </head>
  <body>
    <div class="current">
       <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/console.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title||'网站管理' %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="wrapper">
    <ul id="navigation">
      <li><%= link_to "管理首页", admin_console_path %></li>
      <li><%= link_to "新下载的", admin_archives_path(:status => Archive::NEW) %></li>
      <li><%= link_to "分析完毕的", admin_archives_path(:status => Archive::ANALYZED) %></li>
      <li><%= link_to "等待验证的", admin_archives_path(:status => Archive::SYNCED) %></li>
      <li><%= link_to "已经被锁定的", admin_archives_path(:status => Archive::LOCKED) %></li>
      <li><%= link_to "验证通过的", admin_archives_path(:status => Archive::OK) %></li>
      <li><%= link_to "删除了的", admin_archives_path(:status => Archive::DELETED) %></li>
      <li><%= link_to "首页", root_path %></li>
    </ul>
    <h1 class="admin-title">网站管理<%= @title.blank? ? '' : "-#{@title}" %></h1>
    <div id="main">
    <div class="section">
    <%= yield %>
    </div>
    </div>
    <div id="side">
      <ul>
        <%= yield :admin_menu %>
        <li><%= link_to '管理首页',admin_console_path %></li>
        <li><%= link_to '管理文章',admin_archives_path %></li>
        <li><%= link_to '管理分类', admin_categories_path %></li>
        <li><%= link_to '网站首页',root_path %></li>
      </ul>
    </div>
    <p class="clear"></p>
  </div>
</body>
</html>